[package]
name = "lilypad-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
clap_complete.workspace = true
lilypad-app = { path = "../lilypad-app" }
lilypad-common = { path = "../lilypad-common" }
rpassword = "7.3"
serde_json.workspace = true
zeroize.workspace = true

[build-dependencies]
winresource.workspace = true

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile.workspace = true
