[package]
name = "lilypad-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
fs2.workspace = true
hex.workspace = true
lilypad-common = { path = "../lilypad-common" }
lilypad-core = { path = "../lilypad-core" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
