[package]
name = "lilypad-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
chacha20poly1305.workspace = true
sha2.workspace = true
argon2.workspace = true
subtle.workspace = true
zeroize.workspace = true

[dev-dependencies]
serde_json.workspace = true
criterion.workspace = true

[[bench]]
name = "crypto"
harness = false
